includes:
  - ../base.yaml
dataset:
  dataset_name: GOODTwitter
model:
  backbone: ACR
  model_layer: 3
  gnn_clf_layer: 0
  global_pool: sum
train:
  num_steps: 10
  mile_stones: [150]
  lr_filternode: 0.0
use_norm: none
average_edge_attn: mean
mitigation_sampling: raw
mitigation_readout: weighted