includes:
  - base.yaml
model:
  model_name: GSAT
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - false
    - 10
    - 0.7
log_file: exp_0
use_readout_norm: none
mitigation_sampling: default