includes:
  - base.yaml
model:
  model_name: DIR
  dim_hidden: 128 # From DIR paper
  dim_ffn: 128
ood:
  ood_alg: DIR
  ood_param: 0.6
  extra_param:
    - false
    - 10.0
train:
  lr: 0.0002
  train_bs: 128
log_file: exp_0
clean_save: true
