includes:
  - base.yaml
model:
  model_name: GSAT
ood:
  ood_alg: GSAT
  ood_param: 0.1
  extra_param:
    - false
    - 10
    - 0.3
train:
  mile_stones:
    - 150
log_file: exp_0
clean_save: true
use_norm: none