includes:
  - base.yaml
model:
  model_name: GSATEntropy
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - false
    - 10
    - 0.01
train:
  mile_stones:
    - 150
  entr_coeff: 0.1
log_file: exp_0
clean_save: true
use_norm: none