includes:
  - base.yaml
model:
  model_name: SMGNN
ood:
  ood_alg: SMGNN
  ood_param: 1
  extra_param:
    - false
    - 10
    - 0.001
train:
  mile_stones:
    - 150
log_file: exp_0
clean_save: true
use_norm: none
