includes:
  - base.yaml
model:
  model_name: GSAT
  global_pool: mean
ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - true
    - 20
    - 0.7
train:
  train_bs: 512
  max_epoch: 100
  lr_filternode: 0.001
  channel_int: null
  weight_decay: 0.05
  channel_weight_decay: 0.05
  combinator_weight_decay: 0.0
  end_temp: 0.6
log_file: exp_0
use_readout_norm: none
mitigation_sampling: default