includes:
  - base.yaml
model:
  model_name: DIR
ood:
  ood_alg: DIR
  ood_param: 0.8 # Causal ratio
  extra_param:
    - false
    - 1e-4 # alpha param (strenght Invariant loss)
train:
  mile_stones:
    - 150
log_file: exp_0
clean_save: true
use_norm: none
use_readout_norm: bn
